import type { Metadata } from "next";
import "./globals.css";
import Header from "../../components/Header";
import localFont from "next/font/local";

const gothamFont = localFont({
  src : [
    {
      path: "./fonts/Gotham-Book.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Gotham-BoldItalic_1.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/Gotham-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: '--font-gotham'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gothamFont.variable} ${gothamFont.className} antialiased`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
